name: lab1
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2022.07.19
  - certifi=2022.9.14
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.3
  - openssl=1.1.1q
  - pip=22.1.2
  - python=3.8.13
  - readline=8.1.2
  - setuptools=63.4.1
  - sqlite=3.39.2
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - charset-normalizer==2.1.1
    - contourpy==1.0.5
    - cycler==0.11.0
    - fonttools==4.37.4
    - idna==3.4
    - kiwisolver==1.4.4
    - matplotlib==3.6.1
    - numpy==1.23.3
    - packaging==21.3
    - pandas==1.5.0
    - pillow==9.2.0
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.2.1
    - requests==2.28.1
    - six==1.16.0
    - torch==1.12.1
    - torchvision==0.13.1
    - typing-extensions==4.3.0
    - urllib3==1.26.12
